---
title: |
  | Identifying Frontiers in Ecological Forecasting with 
  | Modern Computational Tools
author:
  - Daniel Ovando^a^*
  - Curry Cunningham^b^
  - Peter Kuriyam^c^
  - Chris Boatright^a^
  - Ray Hilborn^a^
date: "`r Sys.Date()`"
output: 
  bookdown::pdf_document2: default
  bookdown::word_document2:
    reference_docx: template.docx
bibliography: "../references.bib"
csl: pnas.csl
params: 
  results_name: ["v1.0.0.9000"]
linkcolor: blue
toc: false
header-includes:
  # - \usepackage{setspace}\doublespacing
  # - \usepackage{lineno}\linenumbers
  # - \usepackage{draftwatermark}
  # - \SetWatermarkText{DRAFT}
  # - \SetWatermarkScale{1}
abstract: |
  Modern computational tools such as machine learning have transformed predictive fields from advertising to weather forecasting. However, these methods are underutilized for managing ecological systems. Salmon are a natural, cultural, and economic keystone of Alaska, and accurate pre-season forecasts of the numbers of sockeye salmon (*Oncorhynchus nerka*), that will return to the river systems of Bristol Bay play an important role in management and harvesting decisions. These predictions are challenging though, given the complex set of dynamic factors that affect salmon. We use data from the salmon populations of Bristol Bay, Alaska, together with a suite of modern forecasting tools, to identify the frontiers in forecast accuracy possible given currently available data. By leveraging dynamic environmental information and correlations between salmon populations, we were able to reduce forecast error by on average 19%. Our results demonstrate the utility and limitations of modern computational tools for applied management of natural resources, even when confronted with the short time series and observation error common in ecological systems.
---

# Author List

Dr. Daniel Ovando
danovan@uw.edu
School of Aquatic and Fishery Sciences
University of Washington

Dr. Curry Cunningham
cjcunningham@alaska.edu
College of Fisheries and Ocean Sciences
University of Alaska Fairbanks
17101 Point Lena Loop Road
Juneau, AK 99801

Dr. Peter Kuriyama
peter.kuriyama@noaa.gov
NOAA Fisheries Southwest Fisheries Science Center
8901 La Jolla Shores Dr, La Jolla, CA 92037

Dr. Christopher Boatright
cboat@uw.edu
School of Aquatic and Fishery Sciences
University of Washington
1122 NE Boat St, Box 355020 Seattle, WA 98195-5020

Dr. Ray Hilborn
hilbornr@gmail.com
School of Aquatic and Fishery Sciences
University of Washington
FSH 352B
1122 NE Boat St, Box 355020 Seattle, WA 98195-5020


# Author Affiliations

^a^School of Aquatic and Fishery Sciences
University of Washington
1122 NE Boat St, Box 355020 Seattle, WA 98195-5020

^b^College of Fisheries and Ocean Sciences
University of Alaska Fairbanks
17101 Point Lena Loop Road
Juneau, AK 99801

^c^NOAA Fisheries Southwest Fisheries Science Center
8901 La Jolla Shores Dr, La Jolla, CA 92037

# Author Contributions

D.O, C.C., and P.C. developed the data, models and code needed to produce results. R.H. and C.B. assisted in the framing of research questions and interpretation of data and results. All authors contributed to the writing of the manuscript.

# Classification

Biological Sciences > Population Biology

# Keywords

Machine learning, predictive modeling, salmon, ecological forecasting

# Significance Statement

The Bristol Bay, Alaska, sockeye salmon (*Oncorhynchus nerka*) population is an economic and ecological marvel, playing a key role in the ecosystems of Alaska and supporting the largest commercial salmon fishery in the world. Pre-season forecasts of the annual returns of these fish are important to both managers and fishing fleets. Computational tools such as machine learning have transformed predictive fields from advertising to weather forecasting. However, these methods are underutilized for managing ecological systems. Using modern computational tools we were able to substantially increase the accuracy of pre-season forecasts for the Bristol Bay sockeye salmon fishery. Our results demonstrate the utility and limitations of modern computational tools for applied management of natural resources, even when confronted with the short time series and observation error common in ecological systems.

